name: .NET CI/CD

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore FileFlower.sln

      - name: Build
        run: dotnet build FileFlower.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test FileFlower.sln --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Publish code coverage (optional)
        if: success() && github.event_name != 'pull_request'
        uses: codecov/codecov-action@v3
        with:
          files: '**/coverage.cobertura.xml'
          fail_ci_if_error: true

  # TODO: enable publish
  # publish:
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   needs: build-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup .NET SDK
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: 6.0.x

  #     - name: Restore dependencies
  #       run: dotnet restore

  #     - name: Build and pack
  #       run: dotnet pack --no-restore --configuration Release -o ./nupkg

  #     - name: Publish to NuGet.org
  #       uses: nuget/setup-nuget@v1
  #       with:
  #         nuget-api-key: ${{ secrets.NUGET_API_KEY }}

  #     - name: Push package
  #       run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
